# git clone https://github.com/academiaonline/simplilearn-dockercoins 
# cd simplilearn-dockercoins/
# git checkout 2021-09
# alias docker='sudo docker'
# docker image build --file Dockerfile-hasher --tag academiaonline/simplilearn-dockercoins:latest-hasher /mnt/
# docker image build --file Dockerfile-rng --tag academiaonline/simplilearn-dockercoins:latest-rng /mnt/
# docker image build --file Dockerfile-webui --tag academiaonline/simplilearn-dockercoins:latest-webui /mnt/
# docker image build --file Dockerfile-worker --tag academiaonline/simplilearn-dockercoins:latest-worker /mnt/
# docker login
# docker image push academiaonline/simplilearn-dockercoins:latest-hasher 
# docker image push academiaonline/simplilearn-dockercoins:latest-rng 
# docker image push academiaonline/simplilearn-dockercoins:latest-webui 
# docker image push academiaonline/simplilearn-dockercoins:latest-worker 

apiVersion: v1
kind: Pod
metadata:
  name: redis-po
spec:
  containers:
    -
      args: 
        - redis-server
      command:
        - docker-entrypoint.sh
      env:
        -
          name: AUTHOR
          value: "Sebastian Colomar"
      image: library/redis:6.2.5-alpine3.14@sha256:649d5317016d601ac7d6a7b7ef56b6d96196fb7df433d10143189084d52ee6f7
      livenessProbe:
        tcpSocket:
          port: 6379
      name: redis-container
      readinessProbe:
        exec:
          command:
            - redis-cli INFO
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests: 
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /data/
          name: redis-volume
          readOnly: false
      workingDir: /data/
  volumes:
    -
      persistentVolumeClaim:
        claimName: redis-pvc
        readOnly: false
      name: redis-volume
