# git clone https://github.com/academiaonline/simplilearn-dockercoins 
# cd simplilearn-dockercoins/
# git checkout 2021-09
# alias docker='sudo docker'
# docker image build --file Dockerfile-hasher --tag academiaonline/simplilearn-dockercoins:latest-hasher /mnt/
# docker image build --file Dockerfile-rng --tag academiaonline/simplilearn-dockercoins:latest-rng /mnt/
# docker image build --file Dockerfile-webui --tag academiaonline/simplilearn-dockercoins:latest-webui /mnt/
# docker image build --file Dockerfile-worker --tag academiaonline/simplilearn-dockercoins:latest-worker /mnt/
# docker login
# docker image push academiaonline/simplilearn-dockercoins:latest-hasher 
# docker image push academiaonline/simplilearn-dockercoins:latest-rng 
# docker image push academiaonline/simplilearn-dockercoins:latest-webui 
# docker image push academiaonline/simplilearn-dockercoins:latest-worker 

# wget https://raw.githubusercontent.com/academiaonline/simplilearn-dockercoins/2021-09/rng/rng.py
# kubectl create cm rng-cm --from-file rng.py --namespace dockercoins

apiVersion: v1
kind: Pod
metadata:
  name: rng-po
spec:
  containers:
    -
      args: 
        - rng.py
      command:
        - python
      env:
        -
          name: AUTHOR
          value: "Sebastian Colomar"
      image: academiaonline/simplilearn-dockercoins:latest-rng
      livenessProbe:
        tcpSocket:
          port: 8080
      name: rng-container
      readinessProbe:
        httpGet:
          path: /
          port: 8080
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests: 
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /app/rng.py
          name: rng-volume
          readOnly: true
          subPath: rng.py
        -
          mountPath: /usr/local/lib/python3.9/__pycache__/
          name: rng-pycache-volume
          readOnly: false
        -
          mountPath: /usr/local/lib/python3.9/http/__pycache__/
          name: rng-http-pycache-volume
          readOnly: false
      workingDir: /app/
  volumes:
    -
      configMap:
        defaultMode: 0400
        items:
          -
            key: rng.py
            mode: 0400
            path: rng.py
        name: rng-cm
      name: rng-volume
    -
      emptyDir:
        medium: Memory
        sizeLimit: 100M
      name: rng-pycache-volume
    -
      emptyDir:
        medium: Memory
        sizeLimit: 100M
      name: rng-http-pycache-volume
      
